TOTAL_PROTEIN_CONSTRAINT_ID = 'TotalProteinConstraint'
P_TOT_DEFAULT = 0.258 #g_protein/g_cdw
CO2_EXHANGE_RXNID = 'EX_co2_e'
GLUCOSE_EXCHANGE_RXNID = 'EX_glc__D_e'
BIOMASS_REACTION = 'BIOMASS_Ec_iML1515_core_75p37M'
OXYGEN_UPTAKE_RXNID = 'EX_o2_e'
ACETATE_EXCRETION_RXNID = 'EX_ac_e'
PHYS_RXN_IDS = [BIOMASS_REACTION, GLUCOSE_EXCHANGE_RXNID, ACETATE_EXCRETION_RXNID, CO2_EXHANGE_RXNID, OXYGEN_UPTAKE_RXNID,
                    'PGI', 'G6PDH2r', 'EDA', 'CS', 'ICL', 'PPC', 'ME1', 'ME2']
# TOTAL_PROTEIN_CONSTRAINT_ID = 'TotalProteinConstraint'
# P_TOT_DEFAULT = 0.258 #g_protein/g_cdw
# CO2_EXHANGE_RXNID = 'EX_co2_e_f'
# GLUCOSE_EXCHANGE_RXNID = 'EX_glc__D_e_b'
# BIOMASS_REACTION = 'BIOMASS_Ec_iML1515_WT_75p37M'
# OXYGEN_UPTAKE_RXNID = 'EX_o2_e_b'
# ACETATE_EXCRETION_RXNID = 'EX_ac_e_f'
# PHYS_RXN_IDS = [BIOMASS_REACTION, GLUCOSE_EXCHANGE_RXNID, 'EX_ac_e_f', 'EX_co2_e_f', 'EX_o2_e_b',
#                     'PGI_f', 'G6PDH2r_f', 'EDA', 'CS', 'ICL', 'PPC', 'ME1', 'ME2']