name: Run Pytest

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9, 3.x]  # 3.x ensures the latest Python version is used

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          os: ${{matrix.os}}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_PAModelpy.txt
          pip install pytest

      - name: Run Pytest
        run: python -m pytest tests/unit_tests
